---
# tasks file for jenkins
- name: Create main directory structure
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: 1000
  loop: ['jenkins_home']

- name: Copy files to build image
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}"
    mode: "0644"
  loop: "{{ build_files }}"
  notify:
    - Rebuild jenkins container
    - Restart jenkins

- name: Template jenkins config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop: "{{ config_files }}"
  notify: Restart jenkins

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers

- name: Check docker jenkins service up and running
  community.docker.docker_stack:
    state: present
    name: jenkins
    compose:
      - "{{ work_dir }}/docker-compose.yml"
