---
# vars file for vault
work_dir: /opt/traefik

directories:
  - { path: letsencrypt, owner: root }

config_files:
  - { src: docker-compose.yaml.j2, dest: docker-compose.yaml }
  - { src: traefik_tls.yml.j2, dest: traefik_tls.yml }
