---
# handlers file for system-hardening
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'
