---
# tasks file for vault
- name: Create a directories if they do not exist
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    mode: '0755'
    owner: root

- name: Copy config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ work_dir }}/{{ item.dest }}"
    mode: "0644"
  loop:
    "{{ config_files }}"

- name: Deploy vault from a compose file
  community.docker.docker_stack:
    state: present
    name: vault
    compose:
      - "{{ work_dir }}/docker-compose.yaml"
