---
# tasks file for system-hardening
- name: Disable passwordless login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart sshd

- name: Disable login to root via ssh
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PermitRootLogin.*$'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart sshd

- name: Turn on the PubkeyAuthentication
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PubkeyAuthentication.*$'
    line: 'PubkeyAuthentication yes'
    state: present
  notify: Restart sshd

- name: Turn off the KbdInteractiveAuthentication
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?KbdInteractiveAuthentication.*$'
    line: 'KbdInteractiveAuthentication no'
    state: present
  notify: Restart sshd

- name: Installing the required packages
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "{{ needed.Debian }}"
    state: present

- name: Installing the required packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'AlmaLinux'
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
    enablerepo: epel
  loop: "{{ needed.CentOS }}"

- name: Update configuration file - /etc/fail2ban/jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Enable fail2ban service
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
